export const FETCH_STATEMENT = 'FETCH_STATEMENT';
export const FETCH_STATEMENT_SUCCESS = 'FETCH_STATEMENT_SUCCESS';
export const FETCH_STATEMENT_FAIL = 'FETCH_STATEMENT_FAIL';
export const FETCH_AUTHOR_ITEMS = 'FETCH_AUTHOR_ITEMS';
export const FETCH_AUTHOR_ITEMS_SUCCESS = 'FETCH_AUTHOR_ITEMS_SUCCESS';
export const FETCH_AUTHOR_ITEMS_FAIL = 'FETCH_AUTHOR_ITEMS_FAIL';
export const FILTER_BY_ITEM = 'FILTER_BY_ITEM';
export const FILTER_BY_STATEMENT_TYPE = 'FILTER_BY_STATEMENT_TYPE';
